// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCustomDomainsByIDReader is a Reader for the DeleteCustomDomainsByID structure.
type DeleteCustomDomainsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCustomDomainsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCustomDomainsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteCustomDomainsByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteCustomDomainsByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteCustomDomainsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteCustomDomainsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteCustomDomainsByIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCustomDomainsByIDOK creates a DeleteCustomDomainsByIDOK with default headers values
func NewDeleteCustomDomainsByIDOK() *DeleteCustomDomainsByIDOK {
	return &DeleteCustomDomainsByIDOK{}
}

/*DeleteCustomDomainsByIDOK handles this case with default header values.

No response was specified
*/
type DeleteCustomDomainsByIDOK struct {
}

func (o *DeleteCustomDomainsByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdOK ", 200)
}

func (o *DeleteCustomDomainsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomDomainsByIDNoContent creates a DeleteCustomDomainsByIDNoContent with default headers values
func NewDeleteCustomDomainsByIDNoContent() *DeleteCustomDomainsByIDNoContent {
	return &DeleteCustomDomainsByIDNoContent{}
}

/*DeleteCustomDomainsByIDNoContent handles this case with default header values.

The custom domain configuration was deleted.
*/
type DeleteCustomDomainsByIDNoContent struct {
}

func (o *DeleteCustomDomainsByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdNoContent ", 204)
}

func (o *DeleteCustomDomainsByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomDomainsByIDBadRequest creates a DeleteCustomDomainsByIDBadRequest with default headers values
func NewDeleteCustomDomainsByIDBadRequest() *DeleteCustomDomainsByIDBadRequest {
	return &DeleteCustomDomainsByIDBadRequest{}
}

/*DeleteCustomDomainsByIDBadRequest handles this case with default header values.

Invalid request URI. The message will vary depending on the cause.
*/
type DeleteCustomDomainsByIDBadRequest struct {
}

func (o *DeleteCustomDomainsByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdBadRequest ", 400)
}

func (o *DeleteCustomDomainsByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomDomainsByIDUnauthorized creates a DeleteCustomDomainsByIDUnauthorized with default headers values
func NewDeleteCustomDomainsByIDUnauthorized() *DeleteCustomDomainsByIDUnauthorized {
	return &DeleteCustomDomainsByIDUnauthorized{}
}

/*DeleteCustomDomainsByIDUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation.
*/
type DeleteCustomDomainsByIDUnauthorized struct {
}

func (o *DeleteCustomDomainsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdUnauthorized ", 401)
}

func (o *DeleteCustomDomainsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomDomainsByIDForbidden creates a DeleteCustomDomainsByIDForbidden with default headers values
func NewDeleteCustomDomainsByIDForbidden() *DeleteCustomDomainsByIDForbidden {
	return &DeleteCustomDomainsByIDForbidden{}
}

/*DeleteCustomDomainsByIDForbidden handles this case with default header values.

The account is not allowed to perform this operation.
*/
type DeleteCustomDomainsByIDForbidden struct {
}

func (o *DeleteCustomDomainsByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdForbidden ", 403)
}

func (o *DeleteCustomDomainsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCustomDomainsByIDTooManyRequests creates a DeleteCustomDomainsByIDTooManyRequests with default headers values
func NewDeleteCustomDomainsByIDTooManyRequests() *DeleteCustomDomainsByIDTooManyRequests {
	return &DeleteCustomDomainsByIDTooManyRequests{}
}

/*DeleteCustomDomainsByIDTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type DeleteCustomDomainsByIDTooManyRequests struct {
}

func (o *DeleteCustomDomainsByIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/custom-domains/{id}][%d] deleteCustomDomainsByIdTooManyRequests ", 429)
}

func (o *DeleteCustomDomainsByIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
