// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteUsersByEmailParams creates a new DeleteUsersByEmailParams object
// with the default values initialized.
func NewDeleteUsersByEmailParams() *DeleteUsersByEmailParams {
	var ()
	return &DeleteUsersByEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUsersByEmailParamsWithTimeout creates a new DeleteUsersByEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUsersByEmailParamsWithTimeout(timeout time.Duration) *DeleteUsersByEmailParams {
	var ()
	return &DeleteUsersByEmailParams{

		timeout: timeout,
	}
}

// NewDeleteUsersByEmailParamsWithContext creates a new DeleteUsersByEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUsersByEmailParamsWithContext(ctx context.Context) *DeleteUsersByEmailParams {
	var ()
	return &DeleteUsersByEmailParams{

		Context: ctx,
	}
}

// NewDeleteUsersByEmailParamsWithHTTPClient creates a new DeleteUsersByEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUsersByEmailParamsWithHTTPClient(client *http.Client) *DeleteUsersByEmailParams {
	var ()
	return &DeleteUsersByEmailParams{
		HTTPClient: client,
	}
}

/*DeleteUsersByEmailParams contains all the parameters to send to the API endpoint
for the delete users by email operation typically these are written to a http.Request
*/
type DeleteUsersByEmailParams struct {

	/*Email
	  The email of the user to delete

	*/
	Email string
	/*ID
	  The id of the connection (currently only database connections are supported)

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete users by email params
func (o *DeleteUsersByEmailParams) WithTimeout(timeout time.Duration) *DeleteUsersByEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete users by email params
func (o *DeleteUsersByEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete users by email params
func (o *DeleteUsersByEmailParams) WithContext(ctx context.Context) *DeleteUsersByEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete users by email params
func (o *DeleteUsersByEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete users by email params
func (o *DeleteUsersByEmailParams) WithHTTPClient(client *http.Client) *DeleteUsersByEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete users by email params
func (o *DeleteUsersByEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the delete users by email params
func (o *DeleteUsersByEmailParams) WithEmail(email string) *DeleteUsersByEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the delete users by email params
func (o *DeleteUsersByEmailParams) SetEmail(email string) {
	o.Email = email
}

// WithID adds the id to the delete users by email params
func (o *DeleteUsersByEmailParams) WithID(id string) *DeleteUsersByEmailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete users by email params
func (o *DeleteUsersByEmailParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUsersByEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {
		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
