// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteGrantsByIDReader is a Reader for the DeleteGrantsByID structure.
type DeleteGrantsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGrantsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteGrantsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteGrantsByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteGrantsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteGrantsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteGrantsByIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGrantsByIDOK creates a DeleteGrantsByIDOK with default headers values
func NewDeleteGrantsByIDOK() *DeleteGrantsByIDOK {
	return &DeleteGrantsByIDOK{}
}

/*DeleteGrantsByIDOK handles this case with default header values.

No response was specified
*/
type DeleteGrantsByIDOK struct {
}

func (o *DeleteGrantsByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/grants/{id][%d] deleteGrantsByIdOK ", 200)
}

func (o *DeleteGrantsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGrantsByIDNoContent creates a DeleteGrantsByIDNoContent with default headers values
func NewDeleteGrantsByIDNoContent() *DeleteGrantsByIDNoContent {
	return &DeleteGrantsByIDNoContent{}
}

/*DeleteGrantsByIDNoContent handles this case with default header values.

The user grant no longer exists.
*/
type DeleteGrantsByIDNoContent struct {
}

func (o *DeleteGrantsByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/grants/{id][%d] deleteGrantsByIdNoContent ", 204)
}

func (o *DeleteGrantsByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGrantsByIDUnauthorized creates a DeleteGrantsByIDUnauthorized with default headers values
func NewDeleteGrantsByIDUnauthorized() *DeleteGrantsByIDUnauthorized {
	return &DeleteGrantsByIDUnauthorized{}
}

/*DeleteGrantsByIDUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type DeleteGrantsByIDUnauthorized struct {
}

func (o *DeleteGrantsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/grants/{id][%d] deleteGrantsByIdUnauthorized ", 401)
}

func (o *DeleteGrantsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGrantsByIDForbidden creates a DeleteGrantsByIDForbidden with default headers values
func NewDeleteGrantsByIDForbidden() *DeleteGrantsByIDForbidden {
	return &DeleteGrantsByIDForbidden{}
}

/*DeleteGrantsByIDForbidden handles this case with default header values.

Insufficient scope, expected any of: delete:grants
*/
type DeleteGrantsByIDForbidden struct {
}

func (o *DeleteGrantsByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/grants/{id][%d] deleteGrantsByIdForbidden ", 403)
}

func (o *DeleteGrantsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteGrantsByIDTooManyRequests creates a DeleteGrantsByIDTooManyRequests with default headers values
func NewDeleteGrantsByIDTooManyRequests() *DeleteGrantsByIDTooManyRequests {
	return &DeleteGrantsByIDTooManyRequests{}
}

/*DeleteGrantsByIDTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type DeleteGrantsByIDTooManyRequests struct {
}

func (o *DeleteGrantsByIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/grants/{id][%d] deleteGrantsByIdTooManyRequests ", 429)
}

func (o *DeleteGrantsByIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
