// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteUserIdentityByUserIDParams creates a new DeleteUserIdentityByUserIDParams object
// with the default values initialized.
func NewDeleteUserIdentityByUserIDParams() *DeleteUserIdentityByUserIDParams {
	var ()
	return &DeleteUserIdentityByUserIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserIdentityByUserIDParamsWithTimeout creates a new DeleteUserIdentityByUserIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserIdentityByUserIDParamsWithTimeout(timeout time.Duration) *DeleteUserIdentityByUserIDParams {
	var ()
	return &DeleteUserIdentityByUserIDParams{

		timeout: timeout,
	}
}

// NewDeleteUserIdentityByUserIDParamsWithContext creates a new DeleteUserIdentityByUserIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUserIdentityByUserIDParamsWithContext(ctx context.Context) *DeleteUserIdentityByUserIDParams {
	var ()
	return &DeleteUserIdentityByUserIDParams{

		Context: ctx,
	}
}

// NewDeleteUserIdentityByUserIDParamsWithHTTPClient creates a new DeleteUserIdentityByUserIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUserIdentityByUserIDParamsWithHTTPClient(client *http.Client) *DeleteUserIdentityByUserIDParams {
	var ()
	return &DeleteUserIdentityByUserIDParams{
		HTTPClient: client,
	}
}

/*DeleteUserIdentityByUserIDParams contains all the parameters to send to the API endpoint
for the delete user identity by user id operation typically these are written to a http.Request
*/
type DeleteUserIdentityByUserIDParams struct {

	/*ID
	  The user_id of the primary user account.

	*/
	ID string
	/*Provider
	  The identity provider of the secondary linked account. (Ex: 'google-oauth2' in <code>google-oauth2|123456789081523216417</code>)

	*/
	Provider string
	/*UserID
	  The unique identifier of the secondary linked account. (Only the id after the '|' pipe. Ex: '123456789081523216417' in <code>google-oauth2|123456789081523216417</code>)

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithTimeout(timeout time.Duration) *DeleteUserIdentityByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithContext(ctx context.Context) *DeleteUserIdentityByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithHTTPClient(client *http.Client) *DeleteUserIdentityByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithID(id string) *DeleteUserIdentityByUserIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetID(id string) {
	o.ID = id
}

// WithProvider adds the provider to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithProvider(provider string) *DeleteUserIdentityByUserIDParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithUserID adds the userID to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) WithUserID(userID string) *DeleteUserIdentityByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete user identity by user id params
func (o *DeleteUserIdentityByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserIdentityByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
