// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteConnectionsByIDReader is a Reader for the DeleteConnectionsByID structure.
type DeleteConnectionsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConnectionsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteConnectionsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteConnectionsByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteConnectionsByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteConnectionsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteConnectionsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteConnectionsByIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteConnectionsByIDOK creates a DeleteConnectionsByIDOK with default headers values
func NewDeleteConnectionsByIDOK() *DeleteConnectionsByIDOK {
	return &DeleteConnectionsByIDOK{}
}

/*DeleteConnectionsByIDOK handles this case with default header values.

No response was specified
*/
type DeleteConnectionsByIDOK struct {
}

func (o *DeleteConnectionsByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdOK ", 200)
}

func (o *DeleteConnectionsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectionsByIDNoContent creates a DeleteConnectionsByIDNoContent with default headers values
func NewDeleteConnectionsByIDNoContent() *DeleteConnectionsByIDNoContent {
	return &DeleteConnectionsByIDNoContent{}
}

/*DeleteConnectionsByIDNoContent handles this case with default header values.

The connection no longer exists.
*/
type DeleteConnectionsByIDNoContent struct {
}

func (o *DeleteConnectionsByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdNoContent ", 204)
}

func (o *DeleteConnectionsByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectionsByIDBadRequest creates a DeleteConnectionsByIDBadRequest with default headers values
func NewDeleteConnectionsByIDBadRequest() *DeleteConnectionsByIDBadRequest {
	return &DeleteConnectionsByIDBadRequest{}
}

/*DeleteConnectionsByIDBadRequest handles this case with default header values.

Invalid request URI. The message will vary depending on the cause.
*/
type DeleteConnectionsByIDBadRequest struct {
}

func (o *DeleteConnectionsByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdBadRequest ", 400)
}

func (o *DeleteConnectionsByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectionsByIDUnauthorized creates a DeleteConnectionsByIDUnauthorized with default headers values
func NewDeleteConnectionsByIDUnauthorized() *DeleteConnectionsByIDUnauthorized {
	return &DeleteConnectionsByIDUnauthorized{}
}

/*DeleteConnectionsByIDUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type DeleteConnectionsByIDUnauthorized struct {
}

func (o *DeleteConnectionsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdUnauthorized ", 401)
}

func (o *DeleteConnectionsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectionsByIDForbidden creates a DeleteConnectionsByIDForbidden with default headers values
func NewDeleteConnectionsByIDForbidden() *DeleteConnectionsByIDForbidden {
	return &DeleteConnectionsByIDForbidden{}
}

/*DeleteConnectionsByIDForbidden handles this case with default header values.

Insufficient scope, expected any of: delete:connections
*/
type DeleteConnectionsByIDForbidden struct {
}

func (o *DeleteConnectionsByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdForbidden ", 403)
}

func (o *DeleteConnectionsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConnectionsByIDTooManyRequests creates a DeleteConnectionsByIDTooManyRequests with default headers values
func NewDeleteConnectionsByIDTooManyRequests() *DeleteConnectionsByIDTooManyRequests {
	return &DeleteConnectionsByIDTooManyRequests{}
}

/*DeleteConnectionsByIDTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type DeleteConnectionsByIDTooManyRequests struct {
}

func (o *DeleteConnectionsByIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/connections/{id}][%d] deleteConnectionsByIdTooManyRequests ", 429)
}

func (o *DeleteConnectionsByIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
