// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRulesByIDReader is a Reader for the DeleteRulesByID structure.
type DeleteRulesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRulesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRulesByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteRulesByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRulesByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteRulesByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteRulesByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteRulesByIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRulesByIDOK creates a DeleteRulesByIDOK with default headers values
func NewDeleteRulesByIDOK() *DeleteRulesByIDOK {
	return &DeleteRulesByIDOK{}
}

/*DeleteRulesByIDOK handles this case with default header values.

No response was specified
*/
type DeleteRulesByIDOK struct {
}

func (o *DeleteRulesByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdOK ", 200)
}

func (o *DeleteRulesByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRulesByIDNoContent creates a DeleteRulesByIDNoContent with default headers values
func NewDeleteRulesByIDNoContent() *DeleteRulesByIDNoContent {
	return &DeleteRulesByIDNoContent{}
}

/*DeleteRulesByIDNoContent handles this case with default header values.

The rule no longer exists.
*/
type DeleteRulesByIDNoContent struct {
}

func (o *DeleteRulesByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdNoContent ", 204)
}

func (o *DeleteRulesByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRulesByIDBadRequest creates a DeleteRulesByIDBadRequest with default headers values
func NewDeleteRulesByIDBadRequest() *DeleteRulesByIDBadRequest {
	return &DeleteRulesByIDBadRequest{}
}

/*DeleteRulesByIDBadRequest handles this case with default header values.

Invalid request URI. The message will vary depending on the cause.
*/
type DeleteRulesByIDBadRequest struct {
}

func (o *DeleteRulesByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdBadRequest ", 400)
}

func (o *DeleteRulesByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRulesByIDUnauthorized creates a DeleteRulesByIDUnauthorized with default headers values
func NewDeleteRulesByIDUnauthorized() *DeleteRulesByIDUnauthorized {
	return &DeleteRulesByIDUnauthorized{}
}

/*DeleteRulesByIDUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type DeleteRulesByIDUnauthorized struct {
}

func (o *DeleteRulesByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdUnauthorized ", 401)
}

func (o *DeleteRulesByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRulesByIDForbidden creates a DeleteRulesByIDForbidden with default headers values
func NewDeleteRulesByIDForbidden() *DeleteRulesByIDForbidden {
	return &DeleteRulesByIDForbidden{}
}

/*DeleteRulesByIDForbidden handles this case with default header values.

Insufficient scope, expected any of: delete:rules
*/
type DeleteRulesByIDForbidden struct {
}

func (o *DeleteRulesByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdForbidden ", 403)
}

func (o *DeleteRulesByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRulesByIDTooManyRequests creates a DeleteRulesByIDTooManyRequests with default headers values
func NewDeleteRulesByIDTooManyRequests() *DeleteRulesByIDTooManyRequests {
	return &DeleteRulesByIDTooManyRequests{}
}

/*DeleteRulesByIDTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type DeleteRulesByIDTooManyRequests struct {
}

func (o *DeleteRulesByIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/rules/{id}][%d] deleteRulesByIdTooManyRequests ", 429)
}

func (o *DeleteRulesByIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
