// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// DeleteUserBlocksByIDReader is a Reader for the DeleteUserBlocksByID structure.
type DeleteUserBlocksByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserBlocksByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteUserBlocksByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteUserBlocksByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteUserBlocksByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteUserBlocksByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteUserBlocksByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteUserBlocksByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewDeleteUserBlocksByIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteUserBlocksByIDOK creates a DeleteUserBlocksByIDOK with default headers values
func NewDeleteUserBlocksByIDOK() *DeleteUserBlocksByIDOK {
	return &DeleteUserBlocksByIDOK{}
}

/*DeleteUserBlocksByIDOK handles this case with default header values.

No response was specified
*/
type DeleteUserBlocksByIDOK struct {
}

func (o *DeleteUserBlocksByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdOK ", 200)
}

func (o *DeleteUserBlocksByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDNoContent creates a DeleteUserBlocksByIDNoContent with default headers values
func NewDeleteUserBlocksByIDNoContent() *DeleteUserBlocksByIDNoContent {
	return &DeleteUserBlocksByIDNoContent{}
}

/*DeleteUserBlocksByIDNoContent handles this case with default header values.

The user was unblocked. See <strong>Response Class</strong> below for schema.
*/
type DeleteUserBlocksByIDNoContent struct {
}

func (o *DeleteUserBlocksByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdNoContent ", 204)
}

func (o *DeleteUserBlocksByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDBadRequest creates a DeleteUserBlocksByIDBadRequest with default headers values
func NewDeleteUserBlocksByIDBadRequest() *DeleteUserBlocksByIDBadRequest {
	return &DeleteUserBlocksByIDBadRequest{}
}

/*DeleteUserBlocksByIDBadRequest handles this case with default header values.

Invalid request body. The message will vary depending on the cause.
*/
type DeleteUserBlocksByIDBadRequest struct {
}

func (o *DeleteUserBlocksByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdBadRequest ", 400)
}

func (o *DeleteUserBlocksByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDUnauthorized creates a DeleteUserBlocksByIDUnauthorized with default headers values
func NewDeleteUserBlocksByIDUnauthorized() *DeleteUserBlocksByIDUnauthorized {
	return &DeleteUserBlocksByIDUnauthorized{}
}

/*DeleteUserBlocksByIDUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type DeleteUserBlocksByIDUnauthorized struct {
}

func (o *DeleteUserBlocksByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdUnauthorized ", 401)
}

func (o *DeleteUserBlocksByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDForbidden creates a DeleteUserBlocksByIDForbidden with default headers values
func NewDeleteUserBlocksByIDForbidden() *DeleteUserBlocksByIDForbidden {
	return &DeleteUserBlocksByIDForbidden{}
}

/*DeleteUserBlocksByIDForbidden handles this case with default header values.

Insufficient scope, expected any of: update:users
*/
type DeleteUserBlocksByIDForbidden struct {
}

func (o *DeleteUserBlocksByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdForbidden ", 403)
}

func (o *DeleteUserBlocksByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDNotFound creates a DeleteUserBlocksByIDNotFound with default headers values
func NewDeleteUserBlocksByIDNotFound() *DeleteUserBlocksByIDNotFound {
	return &DeleteUserBlocksByIDNotFound{}
}

/*DeleteUserBlocksByIDNotFound handles this case with default header values.

The user does not exist.
*/
type DeleteUserBlocksByIDNotFound struct {
}

func (o *DeleteUserBlocksByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdNotFound ", 404)
}

func (o *DeleteUserBlocksByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserBlocksByIDTooManyRequests creates a DeleteUserBlocksByIDTooManyRequests with default headers values
func NewDeleteUserBlocksByIDTooManyRequests() *DeleteUserBlocksByIDTooManyRequests {
	return &DeleteUserBlocksByIDTooManyRequests{}
}

/*DeleteUserBlocksByIDTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type DeleteUserBlocksByIDTooManyRequests struct {
}

func (o *DeleteUserBlocksByIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/user-blocks/{id}][%d] deleteUserBlocksByIdTooManyRequests ", 429)
}

func (o *DeleteUserBlocksByIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
