// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteResourceServersByIDParams creates a new DeleteResourceServersByIDParams object
// with the default values initialized.
func NewDeleteResourceServersByIDParams() *DeleteResourceServersByIDParams {
	var ()
	return &DeleteResourceServersByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteResourceServersByIDParamsWithTimeout creates a new DeleteResourceServersByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteResourceServersByIDParamsWithTimeout(timeout time.Duration) *DeleteResourceServersByIDParams {
	var ()
	return &DeleteResourceServersByIDParams{

		timeout: timeout,
	}
}

// NewDeleteResourceServersByIDParamsWithContext creates a new DeleteResourceServersByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteResourceServersByIDParamsWithContext(ctx context.Context) *DeleteResourceServersByIDParams {
	var ()
	return &DeleteResourceServersByIDParams{

		Context: ctx,
	}
}

// NewDeleteResourceServersByIDParamsWithHTTPClient creates a new DeleteResourceServersByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteResourceServersByIDParamsWithHTTPClient(client *http.Client) *DeleteResourceServersByIDParams {
	var ()
	return &DeleteResourceServersByIDParams{
		HTTPClient: client,
	}
}

/*DeleteResourceServersByIDParams contains all the parameters to send to the API endpoint
for the delete resource servers by id operation typically these are written to a http.Request
*/
type DeleteResourceServersByIDParams struct {

	/*ID
	  The id or the audience of the resource server to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) WithTimeout(timeout time.Duration) *DeleteResourceServersByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) WithContext(ctx context.Context) *DeleteResourceServersByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) WithHTTPClient(client *http.Client) *DeleteResourceServersByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) WithID(id string) *DeleteResourceServersByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete resource servers by id params
func (o *DeleteResourceServersByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteResourceServersByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
