// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewDeleteClientsByIDParams creates a new DeleteClientsByIDParams object
// with the default values initialized.
func NewDeleteClientsByIDParams() *DeleteClientsByIDParams {
	var ()
	return &DeleteClientsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClientsByIDParamsWithTimeout creates a new DeleteClientsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteClientsByIDParamsWithTimeout(timeout time.Duration) *DeleteClientsByIDParams {
	var ()
	return &DeleteClientsByIDParams{

		timeout: timeout,
	}
}

// NewDeleteClientsByIDParamsWithContext creates a new DeleteClientsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteClientsByIDParamsWithContext(ctx context.Context) *DeleteClientsByIDParams {
	var ()
	return &DeleteClientsByIDParams{

		Context: ctx,
	}
}

// NewDeleteClientsByIDParamsWithHTTPClient creates a new DeleteClientsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteClientsByIDParamsWithHTTPClient(client *http.Client) *DeleteClientsByIDParams {
	var ()
	return &DeleteClientsByIDParams{
		HTTPClient: client,
	}
}

/*DeleteClientsByIDParams contains all the parameters to send to the API endpoint
for the delete clients by id operation typically these are written to a http.Request
*/
type DeleteClientsByIDParams struct {

	/*ID
	  The id of the client to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete clients by id params
func (o *DeleteClientsByIDParams) WithTimeout(timeout time.Duration) *DeleteClientsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete clients by id params
func (o *DeleteClientsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete clients by id params
func (o *DeleteClientsByIDParams) WithContext(ctx context.Context) *DeleteClientsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete clients by id params
func (o *DeleteClientsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete clients by id params
func (o *DeleteClientsByIDParams) WithHTTPClient(client *http.Client) *DeleteClientsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete clients by id params
func (o *DeleteClientsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete clients by id params
func (o *DeleteClientsByIDParams) WithID(id string) *DeleteClientsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete clients by id params
func (o *DeleteClientsByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClientsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
