// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// GetUserBlocksReader is a Reader for the GetUserBlocks structure.
type GetUserBlocksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserBlocksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserBlocksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetUserBlocksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetUserBlocksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetUserBlocksForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewGetUserBlocksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserBlocksOK creates a GetUserBlocksOK with default headers values
func NewGetUserBlocksOK() *GetUserBlocksOK {
	return &GetUserBlocksOK{}
}

/*GetUserBlocksOK handles this case with default header values.

The user was retrieved. See <strong>Response Class</strong> below for schema.
*/
type GetUserBlocksOK struct {
	Payload *models.GetUserBlocksResponse
}

func (o *GetUserBlocksOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/user-blocks][%d] getUserBlocksOK  %+v", 200, o.Payload)
}

func (o *GetUserBlocksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetUserBlocksResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserBlocksBadRequest creates a GetUserBlocksBadRequest with default headers values
func NewGetUserBlocksBadRequest() *GetUserBlocksBadRequest {
	return &GetUserBlocksBadRequest{}
}

/*GetUserBlocksBadRequest handles this case with default header values.

Invalid request query string. The message will vary depending on the cause.
*/
type GetUserBlocksBadRequest struct {
}

func (o *GetUserBlocksBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/user-blocks][%d] getUserBlocksBadRequest ", 400)
}

func (o *GetUserBlocksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserBlocksUnauthorized creates a GetUserBlocksUnauthorized with default headers values
func NewGetUserBlocksUnauthorized() *GetUserBlocksUnauthorized {
	return &GetUserBlocksUnauthorized{}
}

/*GetUserBlocksUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type GetUserBlocksUnauthorized struct {
}

func (o *GetUserBlocksUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/user-blocks][%d] getUserBlocksUnauthorized ", 401)
}

func (o *GetUserBlocksUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserBlocksForbidden creates a GetUserBlocksForbidden with default headers values
func NewGetUserBlocksForbidden() *GetUserBlocksForbidden {
	return &GetUserBlocksForbidden{}
}

/*GetUserBlocksForbidden handles this case with default header values.

Insufficient scope, expected any of: read:users
*/
type GetUserBlocksForbidden struct {
}

func (o *GetUserBlocksForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/user-blocks][%d] getUserBlocksForbidden ", 403)
}

func (o *GetUserBlocksForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUserBlocksTooManyRequests creates a GetUserBlocksTooManyRequests with default headers values
func NewGetUserBlocksTooManyRequests() *GetUserBlocksTooManyRequests {
	return &GetUserBlocksTooManyRequests{}
}

/*GetUserBlocksTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type GetUserBlocksTooManyRequests struct {
}

func (o *GetUserBlocksTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /api/v2/user-blocks][%d] getUserBlocksTooManyRequests ", 429)
}

func (o *GetUserBlocksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
