// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// GetEnrollmentsByIDReader is a Reader for the GetEnrollmentsByID structure.
type GetEnrollmentsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnrollmentsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEnrollmentsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetEnrollmentsByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetEnrollmentsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetEnrollmentsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEnrollmentsByIDOK creates a GetEnrollmentsByIDOK with default headers values
func NewGetEnrollmentsByIDOK() *GetEnrollmentsByIDOK {
	return &GetEnrollmentsByIDOK{}
}

/*GetEnrollmentsByIDOK handles this case with default header values.

Succeed.
*/
type GetEnrollmentsByIDOK struct {
	Payload *models.GetEnrollmentsByIDResponse
}

func (o *GetEnrollmentsByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/guardian/enrollments/{id}][%d] getEnrollmentsByIdOK  %+v", 200, o.Payload)
}

func (o *GetEnrollmentsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetEnrollmentsByIDResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnrollmentsByIDBadRequest creates a GetEnrollmentsByIDBadRequest with default headers values
func NewGetEnrollmentsByIDBadRequest() *GetEnrollmentsByIDBadRequest {
	return &GetEnrollmentsByIDBadRequest{}
}

/*GetEnrollmentsByIDBadRequest handles this case with default header values.

Invalid input based on schemas.
*/
type GetEnrollmentsByIDBadRequest struct {
}

func (o *GetEnrollmentsByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/guardian/enrollments/{id}][%d] getEnrollmentsByIdBadRequest ", 400)
}

func (o *GetEnrollmentsByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentsByIDUnauthorized creates a GetEnrollmentsByIDUnauthorized with default headers values
func NewGetEnrollmentsByIDUnauthorized() *GetEnrollmentsByIDUnauthorized {
	return &GetEnrollmentsByIDUnauthorized{}
}

/*GetEnrollmentsByIDUnauthorized handles this case with default header values.

Token has expired or signature is invalid
*/
type GetEnrollmentsByIDUnauthorized struct {
}

func (o *GetEnrollmentsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/guardian/enrollments/{id}][%d] getEnrollmentsByIdUnauthorized ", 401)
}

func (o *GetEnrollmentsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEnrollmentsByIDForbidden creates a GetEnrollmentsByIDForbidden with default headers values
func NewGetEnrollmentsByIDForbidden() *GetEnrollmentsByIDForbidden {
	return &GetEnrollmentsByIDForbidden{}
}

/*GetEnrollmentsByIDForbidden handles this case with default header values.

Insufficient scope
*/
type GetEnrollmentsByIDForbidden struct {
}

func (o *GetEnrollmentsByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/guardian/enrollments/{id}][%d] getEnrollmentsByIdForbidden ", 403)
}

func (o *GetEnrollmentsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
