// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewGetUserBlocksParams creates a new GetUserBlocksParams object
// with the default values initialized.
func NewGetUserBlocksParams() *GetUserBlocksParams {
	var ()
	return &GetUserBlocksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserBlocksParamsWithTimeout creates a new GetUserBlocksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserBlocksParamsWithTimeout(timeout time.Duration) *GetUserBlocksParams {
	var ()
	return &GetUserBlocksParams{

		timeout: timeout,
	}
}

// NewGetUserBlocksParamsWithContext creates a new GetUserBlocksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserBlocksParamsWithContext(ctx context.Context) *GetUserBlocksParams {
	var ()
	return &GetUserBlocksParams{

		Context: ctx,
	}
}

// NewGetUserBlocksParamsWithHTTPClient creates a new GetUserBlocksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserBlocksParamsWithHTTPClient(client *http.Client) *GetUserBlocksParams {
	var ()
	return &GetUserBlocksParams{
		HTTPClient: client,
	}
}

/*GetUserBlocksParams contains all the parameters to send to the API endpoint
for the get user blocks operation typically these are written to a http.Request
*/
type GetUserBlocksParams struct {

	/*Identifier
	  Should be any of: username, phone_number, email.

	*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user blocks params
func (o *GetUserBlocksParams) WithTimeout(timeout time.Duration) *GetUserBlocksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user blocks params
func (o *GetUserBlocksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user blocks params
func (o *GetUserBlocksParams) WithContext(ctx context.Context) *GetUserBlocksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user blocks params
func (o *GetUserBlocksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user blocks params
func (o *GetUserBlocksParams) WithHTTPClient(client *http.Client) *GetUserBlocksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user blocks params
func (o *GetUserBlocksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIdentifier adds the identifier to the get user blocks params
func (o *GetUserBlocksParams) WithIdentifier(identifier string) *GetUserBlocksParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get user blocks params
func (o *GetUserBlocksParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserBlocksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param identifier
	qrIdentifier := o.Identifier
	qIdentifier := qrIdentifier
	if qIdentifier != "" {
		if err := r.SetQueryParam("identifier", qIdentifier); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
