// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// GetUsersByEmailReader is a Reader for the GetUsersByEmail structure.
type GetUsersByEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersByEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUsersByEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetUsersByEmailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetUsersByEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetUsersByEmailForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewGetUsersByEmailTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUsersByEmailOK creates a GetUsersByEmailOK with default headers values
func NewGetUsersByEmailOK() *GetUsersByEmailOK {
	return &GetUsersByEmailOK{}
}

/*GetUsersByEmailOK handles this case with default header values.

The users were retrieved. See <strong>Response Class</strong> below for schema.
*/
type GetUsersByEmailOK struct {
	Payload []*models.GetUsersByEmailResponse
}

func (o *GetUsersByEmailOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/users-by-email][%d] getUsersByEmailOK  %+v", 200, o.Payload)
}

func (o *GetUsersByEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersByEmailBadRequest creates a GetUsersByEmailBadRequest with default headers values
func NewGetUsersByEmailBadRequest() *GetUsersByEmailBadRequest {
	return &GetUsersByEmailBadRequest{}
}

/*GetUsersByEmailBadRequest handles this case with default header values.

Invalid request query string. The message will vary depending on the cause.
*/
type GetUsersByEmailBadRequest struct {
}

func (o *GetUsersByEmailBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/users-by-email][%d] getUsersByEmailBadRequest ", 400)
}

func (o *GetUsersByEmailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsersByEmailUnauthorized creates a GetUsersByEmailUnauthorized with default headers values
func NewGetUsersByEmailUnauthorized() *GetUsersByEmailUnauthorized {
	return &GetUsersByEmailUnauthorized{}
}

/*GetUsersByEmailUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type GetUsersByEmailUnauthorized struct {
}

func (o *GetUsersByEmailUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/users-by-email][%d] getUsersByEmailUnauthorized ", 401)
}

func (o *GetUsersByEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsersByEmailForbidden creates a GetUsersByEmailForbidden with default headers values
func NewGetUsersByEmailForbidden() *GetUsersByEmailForbidden {
	return &GetUsersByEmailForbidden{}
}

/*GetUsersByEmailForbidden handles this case with default header values.

Insufficient scope, expected any of: read:users
*/
type GetUsersByEmailForbidden struct {
}

func (o *GetUsersByEmailForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/users-by-email][%d] getUsersByEmailForbidden ", 403)
}

func (o *GetUsersByEmailForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsersByEmailTooManyRequests creates a GetUsersByEmailTooManyRequests with default headers values
func NewGetUsersByEmailTooManyRequests() *GetUsersByEmailTooManyRequests {
	return &GetUsersByEmailTooManyRequests{}
}

/*GetUsersByEmailTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type GetUsersByEmailTooManyRequests struct {
}

func (o *GetUsersByEmailTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /api/v2/users-by-email][%d] getUsersByEmailTooManyRequests ", 429)
}

func (o *GetUsersByEmailTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
