// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPatchRulesByIDParams creates a new PatchRulesByIDParams object
// with the default values initialized.
func NewPatchRulesByIDParams() *PatchRulesByIDParams {
	var ()
	return &PatchRulesByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchRulesByIDParamsWithTimeout creates a new PatchRulesByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchRulesByIDParamsWithTimeout(timeout time.Duration) *PatchRulesByIDParams {
	var ()
	return &PatchRulesByIDParams{

		timeout: timeout,
	}
}

// NewPatchRulesByIDParamsWithContext creates a new PatchRulesByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchRulesByIDParamsWithContext(ctx context.Context) *PatchRulesByIDParams {
	var ()
	return &PatchRulesByIDParams{

		Context: ctx,
	}
}

// NewPatchRulesByIDParamsWithHTTPClient creates a new PatchRulesByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchRulesByIDParamsWithHTTPClient(client *http.Client) *PatchRulesByIDParams {
	var ()
	return &PatchRulesByIDParams{
		HTTPClient: client,
	}
}

/*PatchRulesByIDParams contains all the parameters to send to the API endpoint
for the patch rules by id operation typically these are written to a http.Request
*/
type PatchRulesByIDParams struct {

	/*Body*/
	Body *models.PatchRulesByIDBody
	/*ID
	  The id of the rule to retrieve

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch rules by id params
func (o *PatchRulesByIDParams) WithTimeout(timeout time.Duration) *PatchRulesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch rules by id params
func (o *PatchRulesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch rules by id params
func (o *PatchRulesByIDParams) WithContext(ctx context.Context) *PatchRulesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch rules by id params
func (o *PatchRulesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch rules by id params
func (o *PatchRulesByIDParams) WithHTTPClient(client *http.Client) *PatchRulesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch rules by id params
func (o *PatchRulesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch rules by id params
func (o *PatchRulesByIDParams) WithBody(body *models.PatchRulesByIDBody) *PatchRulesByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch rules by id params
func (o *PatchRulesByIDParams) SetBody(body *models.PatchRulesByIDBody) {
	o.Body = body
}

// WithID adds the id to the patch rules by id params
func (o *PatchRulesByIDParams) WithID(id string) *PatchRulesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch rules by id params
func (o *PatchRulesByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchRulesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
