// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPatchResourceServersByIDParams creates a new PatchResourceServersByIDParams object
// with the default values initialized.
func NewPatchResourceServersByIDParams() *PatchResourceServersByIDParams {
	var ()
	return &PatchResourceServersByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchResourceServersByIDParamsWithTimeout creates a new PatchResourceServersByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchResourceServersByIDParamsWithTimeout(timeout time.Duration) *PatchResourceServersByIDParams {
	var ()
	return &PatchResourceServersByIDParams{

		timeout: timeout,
	}
}

// NewPatchResourceServersByIDParamsWithContext creates a new PatchResourceServersByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchResourceServersByIDParamsWithContext(ctx context.Context) *PatchResourceServersByIDParams {
	var ()
	return &PatchResourceServersByIDParams{

		Context: ctx,
	}
}

// NewPatchResourceServersByIDParamsWithHTTPClient creates a new PatchResourceServersByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchResourceServersByIDParamsWithHTTPClient(client *http.Client) *PatchResourceServersByIDParams {
	var ()
	return &PatchResourceServersByIDParams{
		HTTPClient: client,
	}
}

/*PatchResourceServersByIDParams contains all the parameters to send to the API endpoint
for the patch resource servers by id operation typically these are written to a http.Request
*/
type PatchResourceServersByIDParams struct {

	/*Body*/
	Body *models.PatchResourceServersByIDBody
	/*ID
	  The id or audience of the resource server to update

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) WithTimeout(timeout time.Duration) *PatchResourceServersByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) WithContext(ctx context.Context) *PatchResourceServersByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) WithHTTPClient(client *http.Client) *PatchResourceServersByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) WithBody(body *models.PatchResourceServersByIDBody) *PatchResourceServersByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) SetBody(body *models.PatchResourceServersByIDBody) {
	o.Body = body
}

// WithID adds the id to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) WithID(id string) *PatchResourceServersByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch resource servers by id params
func (o *PatchResourceServersByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchResourceServersByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
