// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PostEmailVerificationReader is a Reader for the PostEmailVerification structure.
type PostEmailVerificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostEmailVerificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostEmailVerificationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPostEmailVerificationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostEmailVerificationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostEmailVerificationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostEmailVerificationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostEmailVerificationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPostEmailVerificationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostEmailVerificationOK creates a PostEmailVerificationOK with default headers values
func NewPostEmailVerificationOK() *PostEmailVerificationOK {
	return &PostEmailVerificationOK{}
}

/*PostEmailVerificationOK handles this case with default header values.

No response was specified
*/
type PostEmailVerificationOK struct {
	Payload *models.PostEmailVerificationResponse
}

func (o *PostEmailVerificationOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationOK  %+v", 200, o.Payload)
}

func (o *PostEmailVerificationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostEmailVerificationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostEmailVerificationCreated creates a PostEmailVerificationCreated with default headers values
func NewPostEmailVerificationCreated() *PostEmailVerificationCreated {
	return &PostEmailVerificationCreated{}
}

/*PostEmailVerificationCreated handles this case with default header values.

The ticket was created.
*/
type PostEmailVerificationCreated struct {
}

func (o *PostEmailVerificationCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationCreated ", 201)
}

func (o *PostEmailVerificationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailVerificationBadRequest creates a PostEmailVerificationBadRequest with default headers values
func NewPostEmailVerificationBadRequest() *PostEmailVerificationBadRequest {
	return &PostEmailVerificationBadRequest{}
}

/*PostEmailVerificationBadRequest handles this case with default header values.

The connection with id {connection_id} does not exist
*/
type PostEmailVerificationBadRequest struct {
}

func (o *PostEmailVerificationBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationBadRequest ", 400)
}

func (o *PostEmailVerificationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailVerificationUnauthorized creates a PostEmailVerificationUnauthorized with default headers values
func NewPostEmailVerificationUnauthorized() *PostEmailVerificationUnauthorized {
	return &PostEmailVerificationUnauthorized{}
}

/*PostEmailVerificationUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type PostEmailVerificationUnauthorized struct {
}

func (o *PostEmailVerificationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationUnauthorized ", 401)
}

func (o *PostEmailVerificationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailVerificationForbidden creates a PostEmailVerificationForbidden with default headers values
func NewPostEmailVerificationForbidden() *PostEmailVerificationForbidden {
	return &PostEmailVerificationForbidden{}
}

/*PostEmailVerificationForbidden handles this case with default header values.

Insufficient scope, expected any of: create:user_tickets
*/
type PostEmailVerificationForbidden struct {
}

func (o *PostEmailVerificationForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationForbidden ", 403)
}

func (o *PostEmailVerificationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailVerificationNotFound creates a PostEmailVerificationNotFound with default headers values
func NewPostEmailVerificationNotFound() *PostEmailVerificationNotFound {
	return &PostEmailVerificationNotFound{}
}

/*PostEmailVerificationNotFound handles this case with default header values.

The user does not exist
*/
type PostEmailVerificationNotFound struct {
}

func (o *PostEmailVerificationNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationNotFound ", 404)
}

func (o *PostEmailVerificationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostEmailVerificationTooManyRequests creates a PostEmailVerificationTooManyRequests with default headers values
func NewPostEmailVerificationTooManyRequests() *PostEmailVerificationTooManyRequests {
	return &PostEmailVerificationTooManyRequests{}
}

/*PostEmailVerificationTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type PostEmailVerificationTooManyRequests struct {
}

func (o *PostEmailVerificationTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v2/tickets/email-verification][%d] postEmailVerificationTooManyRequests ", 429)
}

func (o *PostEmailVerificationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
