// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PostClientsReader is a Reader for the PostClients structure.
type PostClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPostClientsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostClientsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostClientsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostClientsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostClientsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPostClientsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostClientsOK creates a PostClientsOK with default headers values
func NewPostClientsOK() *PostClientsOK {
	return &PostClientsOK{}
}

/*PostClientsOK handles this case with default header values.

No response was specified
*/
type PostClientsOK struct {
	Payload *models.PostClientsResponse
}

func (o *PostClientsOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsOK  %+v", 200, o.Payload)
}

func (o *PostClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostClientsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostClientsCreated creates a PostClientsCreated with default headers values
func NewPostClientsCreated() *PostClientsCreated {
	return &PostClientsCreated{}
}

/*PostClientsCreated handles this case with default header values.

The client was created. See <strong>Response Class</strong> below for schema.
*/
type PostClientsCreated struct {
}

func (o *PostClientsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsCreated ", 201)
}

func (o *PostClientsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClientsBadRequest creates a PostClientsBadRequest with default headers values
func NewPostClientsBadRequest() *PostClientsBadRequest {
	return &PostClientsBadRequest{}
}

/*PostClientsBadRequest handles this case with default header values.

Invalid request body. The message will vary depending on the cause.
*/
type PostClientsBadRequest struct {
}

func (o *PostClientsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsBadRequest ", 400)
}

func (o *PostClientsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClientsUnauthorized creates a PostClientsUnauthorized with default headers values
func NewPostClientsUnauthorized() *PostClientsUnauthorized {
	return &PostClientsUnauthorized{}
}

/*PostClientsUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type PostClientsUnauthorized struct {
}

func (o *PostClientsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsUnauthorized ", 401)
}

func (o *PostClientsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClientsForbidden creates a PostClientsForbidden with default headers values
func NewPostClientsForbidden() *PostClientsForbidden {
	return &PostClientsForbidden{}
}

/*PostClientsForbidden handles this case with default header values.

Insufficient scope, expected any of: create:clients
*/
type PostClientsForbidden struct {
}

func (o *PostClientsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsForbidden ", 403)
}

func (o *PostClientsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClientsConflict creates a PostClientsConflict with default headers values
func NewPostClientsConflict() *PostClientsConflict {
	return &PostClientsConflict{}
}

/*PostClientsConflict handles this case with default header values.

There is another client with the same alias.
*/
type PostClientsConflict struct {
}

func (o *PostClientsConflict) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsConflict ", 409)
}

func (o *PostClientsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClientsTooManyRequests creates a PostClientsTooManyRequests with default headers values
func NewPostClientsTooManyRequests() *PostClientsTooManyRequests {
	return &PostClientsTooManyRequests{}
}

/*PostClientsTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type PostClientsTooManyRequests struct {
}

func (o *PostClientsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v2/clients][%d] postClientsTooManyRequests ", 429)
}

func (o *PostClientsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
