// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostVerifyParams creates a new PostVerifyParams object
// with the default values initialized.
func NewPostVerifyParams() *PostVerifyParams {
	var ()
	return &PostVerifyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVerifyParamsWithTimeout creates a new PostVerifyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVerifyParamsWithTimeout(timeout time.Duration) *PostVerifyParams {
	var ()
	return &PostVerifyParams{

		timeout: timeout,
	}
}

// NewPostVerifyParamsWithContext creates a new PostVerifyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVerifyParamsWithContext(ctx context.Context) *PostVerifyParams {
	var ()
	return &PostVerifyParams{

		Context: ctx,
	}
}

// NewPostVerifyParamsWithHTTPClient creates a new PostVerifyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostVerifyParamsWithHTTPClient(client *http.Client) *PostVerifyParams {
	var ()
	return &PostVerifyParams{
		HTTPClient: client,
	}
}

/*PostVerifyParams contains all the parameters to send to the API endpoint
for the post verify operation typically these are written to a http.Request
*/
type PostVerifyParams struct {

	/*ID
	  The id of the custom domain to verify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post verify params
func (o *PostVerifyParams) WithTimeout(timeout time.Duration) *PostVerifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post verify params
func (o *PostVerifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post verify params
func (o *PostVerifyParams) WithContext(ctx context.Context) *PostVerifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post verify params
func (o *PostVerifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post verify params
func (o *PostVerifyParams) WithHTTPClient(client *http.Client) *PostVerifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post verify params
func (o *PostVerifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post verify params
func (o *PostVerifyParams) WithID(id string) *PostVerifyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post verify params
func (o *PostVerifyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostVerifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
