// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PostVerificationEmailReader is a Reader for the PostVerificationEmail structure.
type PostVerificationEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostVerificationEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostVerificationEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPostVerificationEmailCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostVerificationEmailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostVerificationEmailUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostVerificationEmailForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPostVerificationEmailTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostVerificationEmailOK creates a PostVerificationEmailOK with default headers values
func NewPostVerificationEmailOK() *PostVerificationEmailOK {
	return &PostVerificationEmailOK{}
}

/*PostVerificationEmailOK handles this case with default header values.

No response was specified
*/
type PostVerificationEmailOK struct {
	Payload *models.PostVerificationEmailResponse
}

func (o *PostVerificationEmailOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailOK  %+v", 200, o.Payload)
}

func (o *PostVerificationEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostVerificationEmailResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostVerificationEmailCreated creates a PostVerificationEmailCreated with default headers values
func NewPostVerificationEmailCreated() *PostVerificationEmailCreated {
	return &PostVerificationEmailCreated{}
}

/*PostVerificationEmailCreated handles this case with default header values.

The job was created. See <strong>Response Class</strong> below for schema.
*/
type PostVerificationEmailCreated struct {
}

func (o *PostVerificationEmailCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailCreated ", 201)
}

func (o *PostVerificationEmailCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostVerificationEmailBadRequest creates a PostVerificationEmailBadRequest with default headers values
func NewPostVerificationEmailBadRequest() *PostVerificationEmailBadRequest {
	return &PostVerificationEmailBadRequest{}
}

/*PostVerificationEmailBadRequest handles this case with default header values.

The connection does not exist
*/
type PostVerificationEmailBadRequest struct {
}

func (o *PostVerificationEmailBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailBadRequest ", 400)
}

func (o *PostVerificationEmailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostVerificationEmailUnauthorized creates a PostVerificationEmailUnauthorized with default headers values
func NewPostVerificationEmailUnauthorized() *PostVerificationEmailUnauthorized {
	return &PostVerificationEmailUnauthorized{}
}

/*PostVerificationEmailUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type PostVerificationEmailUnauthorized struct {
}

func (o *PostVerificationEmailUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailUnauthorized ", 401)
}

func (o *PostVerificationEmailUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostVerificationEmailForbidden creates a PostVerificationEmailForbidden with default headers values
func NewPostVerificationEmailForbidden() *PostVerificationEmailForbidden {
	return &PostVerificationEmailForbidden{}
}

/*PostVerificationEmailForbidden handles this case with default header values.

Insufficient scope, expected any of: update:users
*/
type PostVerificationEmailForbidden struct {
}

func (o *PostVerificationEmailForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailForbidden ", 403)
}

func (o *PostVerificationEmailForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostVerificationEmailTooManyRequests creates a PostVerificationEmailTooManyRequests with default headers values
func NewPostVerificationEmailTooManyRequests() *PostVerificationEmailTooManyRequests {
	return &PostVerificationEmailTooManyRequests{}
}

/*PostVerificationEmailTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type PostVerificationEmailTooManyRequests struct {
}

func (o *PostVerificationEmailTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/verification-email][%d] postVerificationEmailTooManyRequests ", 429)
}

func (o *PostVerificationEmailTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
