// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostTicketParams creates a new PostTicketParams object
// with the default values initialized.
func NewPostTicketParams() *PostTicketParams {
	var ()
	return &PostTicketParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTicketParamsWithTimeout creates a new PostTicketParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTicketParamsWithTimeout(timeout time.Duration) *PostTicketParams {
	var ()
	return &PostTicketParams{

		timeout: timeout,
	}
}

// NewPostTicketParamsWithContext creates a new PostTicketParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTicketParamsWithContext(ctx context.Context) *PostTicketParams {
	var ()
	return &PostTicketParams{

		Context: ctx,
	}
}

// NewPostTicketParamsWithHTTPClient creates a new PostTicketParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTicketParamsWithHTTPClient(client *http.Client) *PostTicketParams {
	var ()
	return &PostTicketParams{
		HTTPClient: client,
	}
}

/*PostTicketParams contains all the parameters to send to the API endpoint
for the post ticket operation typically these are written to a http.Request
*/
type PostTicketParams struct {

	/*Body*/
	Body *models.PostTicketBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post ticket params
func (o *PostTicketParams) WithTimeout(timeout time.Duration) *PostTicketParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ticket params
func (o *PostTicketParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ticket params
func (o *PostTicketParams) WithContext(ctx context.Context) *PostTicketParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ticket params
func (o *PostTicketParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ticket params
func (o *PostTicketParams) WithHTTPClient(client *http.Client) *PostTicketParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ticket params
func (o *PostTicketParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post ticket params
func (o *PostTicketParams) WithBody(body *models.PostTicketBody) *PostTicketParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post ticket params
func (o *PostTicketParams) SetBody(body *models.PostTicketBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostTicketParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
