// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	models "bitbucket.org/troyko/go-auth0-management-api/models"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PostUsersExportsReader is a Reader for the PostUsersExports structure.
type PostUsersExportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUsersExportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostUsersExportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPostUsersExportsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostUsersExportsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostUsersExportsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostUsersExportsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPostUsersExportsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUsersExportsOK creates a PostUsersExportsOK with default headers values
func NewPostUsersExportsOK() *PostUsersExportsOK {
	return &PostUsersExportsOK{}
}

/*PostUsersExportsOK handles this case with default header values.

No response was specified
*/
type PostUsersExportsOK struct {
	Payload *models.PostUsersExportsResponse
}

func (o *PostUsersExportsOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsOK  %+v", 200, o.Payload)
}

func (o *PostUsersExportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostUsersExportsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUsersExportsCreated creates a PostUsersExportsCreated with default headers values
func NewPostUsersExportsCreated() *PostUsersExportsCreated {
	return &PostUsersExportsCreated{}
}

/*PostUsersExportsCreated handles this case with default header values.

The job was created. See <strong>Response Class</strong> below for schema.
*/
type PostUsersExportsCreated struct {
}

func (o *PostUsersExportsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsCreated ", 201)
}

func (o *PostUsersExportsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersExportsBadRequest creates a PostUsersExportsBadRequest with default headers values
func NewPostUsersExportsBadRequest() *PostUsersExportsBadRequest {
	return &PostUsersExportsBadRequest{}
}

/*PostUsersExportsBadRequest handles this case with default header values.

The connection does not exist
*/
type PostUsersExportsBadRequest struct {
}

func (o *PostUsersExportsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsBadRequest ", 400)
}

func (o *PostUsersExportsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersExportsUnauthorized creates a PostUsersExportsUnauthorized with default headers values
func NewPostUsersExportsUnauthorized() *PostUsersExportsUnauthorized {
	return &PostUsersExportsUnauthorized{}
}

/*PostUsersExportsUnauthorized handles this case with default header values.

Invalid signature received for JSON Web Token validation
*/
type PostUsersExportsUnauthorized struct {
}

func (o *PostUsersExportsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsUnauthorized ", 401)
}

func (o *PostUsersExportsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersExportsForbidden creates a PostUsersExportsForbidden with default headers values
func NewPostUsersExportsForbidden() *PostUsersExportsForbidden {
	return &PostUsersExportsForbidden{}
}

/*PostUsersExportsForbidden handles this case with default header values.

Insufficient scope, expected any of: read:users
*/
type PostUsersExportsForbidden struct {
}

func (o *PostUsersExportsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsForbidden ", 403)
}

func (o *PostUsersExportsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersExportsTooManyRequests creates a PostUsersExportsTooManyRequests with default headers values
func NewPostUsersExportsTooManyRequests() *PostUsersExportsTooManyRequests {
	return &PostUsersExportsTooManyRequests{}
}

/*PostUsersExportsTooManyRequests handles this case with default header values.

Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
*/
type PostUsersExportsTooManyRequests struct {
}

func (o *PostUsersExportsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v2/jobs/users-exports][%d] postUsersExportsTooManyRequests ", 429)
}

func (o *PostUsersExportsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
