// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSettingsResponseChangePassword Change Password page customization
// swagger:model get_settings_response_change_password
type GetSettingsResponseChangePassword struct {

	// <code>true</code> to use the custom change password html, <code>false</code> otherwise (default: <code>false</code>)
	Enabled *bool `json:"enabled,omitempty"`

	// Replace default change password page with a custom HTML (<a href='https://github.com/Shopify/liquid/wiki/Liquid-for-Designers' target='_new'>Liquid syntax</a> is supported)
	HTML string `json:"html,omitempty"`
}

// Validate validates this get settings response change password
func (m *GetSettingsResponseChangePassword) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetSettingsResponseChangePassword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSettingsResponseChangePassword) UnmarshalBinary(b []byte) error {
	var res GetSettingsResponseChangePassword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
