// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetCustomDomainsByIDResponse get custom domains by id response
// swagger:model get_custom-domains_by_id_response
type GetCustomDomainsByIDResponse struct {

	// The id of the custom domain.
	// Required: true
	CustomDomainID *string `json:"custom_domain_id"`

	// The custom domain.
	// Required: true
	Domain *string `json:"domain"`

	// The intermediate address.
	OriginDomainName *string `json:"origin_domain_name,omitempty"`

	// <code>true</code> if the domain was marked as "primary", <code>false</code> otherwise.
	// Required: true
	Primary bool `json:"primary"`

	// The custom domain configuration status.
	// Required: true
	// Enum: [disabled pending pending_verification ready]
	Status *string `json:"status"`

	// The custom domain provisioning type.
	// Required: true
	// Enum: [auth0_managed_certs self_managed_certs]
	Type *string `json:"type"`

	// verification
	Verification *GetCustomDomainsByIDResponseVerification `json:"verification,omitempty"`
}

// Validate validates this get custom domains by id response
func (m *GetCustomDomainsByIDResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomDomainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrimary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetCustomDomainsByIDResponse) validateCustomDomainID(formats strfmt.Registry) error {

	if err := validate.Required("custom_domain_id", "body", m.CustomDomainID); err != nil {
		return err
	}

	return nil
}

func (m *GetCustomDomainsByIDResponse) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *GetCustomDomainsByIDResponse) validatePrimary(formats strfmt.Registry) error {

	if err := validate.Required("primary", "body", bool(m.Primary)); err != nil {
		return err
	}

	return nil
}

var getCustomDomainsByIdResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disabled","pending","pending_verification","ready"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getCustomDomainsByIdResponseTypeStatusPropEnum = append(getCustomDomainsByIdResponseTypeStatusPropEnum, v)
	}
}

const (

	// GetCustomDomainsByIDResponseStatusDisabled captures enum value "disabled"
	GetCustomDomainsByIDResponseStatusDisabled string = "disabled"

	// GetCustomDomainsByIDResponseStatusPending captures enum value "pending"
	GetCustomDomainsByIDResponseStatusPending string = "pending"

	// GetCustomDomainsByIDResponseStatusPendingVerification captures enum value "pending_verification"
	GetCustomDomainsByIDResponseStatusPendingVerification string = "pending_verification"

	// GetCustomDomainsByIDResponseStatusReady captures enum value "ready"
	GetCustomDomainsByIDResponseStatusReady string = "ready"
)

// prop value enum
func (m *GetCustomDomainsByIDResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, getCustomDomainsByIdResponseTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *GetCustomDomainsByIDResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

var getCustomDomainsByIdResponseTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["auth0_managed_certs","self_managed_certs"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getCustomDomainsByIdResponseTypeTypePropEnum = append(getCustomDomainsByIdResponseTypeTypePropEnum, v)
	}
}

const (

	// GetCustomDomainsByIDResponseTypeAuth0ManagedCerts captures enum value "auth0_managed_certs"
	GetCustomDomainsByIDResponseTypeAuth0ManagedCerts string = "auth0_managed_certs"

	// GetCustomDomainsByIDResponseTypeSelfManagedCerts captures enum value "self_managed_certs"
	GetCustomDomainsByIDResponseTypeSelfManagedCerts string = "self_managed_certs"
)

// prop value enum
func (m *GetCustomDomainsByIDResponse) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, getCustomDomainsByIdResponseTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *GetCustomDomainsByIDResponse) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

func (m *GetCustomDomainsByIDResponse) validateVerification(formats strfmt.Registry) error {

	if swag.IsZero(m.Verification) { // not required
		return nil
	}

	if m.Verification != nil {
		if err := m.Verification.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verification")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetCustomDomainsByIDResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetCustomDomainsByIDResponse) UnmarshalBinary(b []byte) error {
	var res GetCustomDomainsByIDResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
