// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetClientsResponseClientMetadata Metadata associated with the client, in the form of an object with string values (max 255 chars).  Maximum of 10 metadata properties allowed.
// swagger:model get_clients_response_client_metadata
type GetClientsResponseClientMetadata interface{}
