// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetConnectionsResponseOptions get connections response options
// swagger:model get_connections_response_options
type GetConnectionsResponseOptions interface{}
