// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchConnectionsByIDBodyOptions The connection's options (depend on the connection strategy)
// swagger:model patch_connections_by_id_body_options
type PatchConnectionsByIDBodyOptions struct {

	// api enable users
	APIEnableUsers *bool `json:"api_enable_users,omitempty"`

	// basic profile
	BasicProfile *bool `json:"basic_profile,omitempty"`

	// ext admin
	ExtAdmin bool `json:"ext_admin,omitempty"`

	// ext agreed terms
	ExtAgreedTerms bool `json:"ext_agreed_terms,omitempty"`

	// ext assigned plans
	ExtAssignedPlans bool `json:"ext_assigned_plans,omitempty"`

	// ext groups
	ExtGroups bool `json:"ext_groups,omitempty"`

	// ext is suspended
	ExtIsSuspended bool `json:"ext_is_suspended,omitempty"`

	// ext profile
	ExtProfile bool `json:"ext_profile,omitempty"`

	// Password strength level
	// Enum: [none low fair good excellent]
	PasswordPolicy string `json:"passwordPolicy,omitempty"`

	// password complexity options
	PasswordComplexityOptions *PatchConnectionsByIDBodyOptionsPasswordComplexityOptions `json:"password_complexity_options,omitempty"`

	// password dictionary
	PasswordDictionary *PatchConnectionsByIDBodyOptionsPasswordDictionary `json:"password_dictionary,omitempty"`

	// password history
	PasswordHistory *PatchConnectionsByIDBodyOptionsPasswordHistory `json:"password_history,omitempty"`

	// password no personal info
	PasswordNoPersonalInfo *PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo `json:"password_no_personal_info,omitempty"`

	// Options for adding parameters in the request to the upstream IdP
	UpstreamParams interface{} `json:"upstream_params,omitempty"`

	// validation
	Validation *PatchConnectionsByIDBodyOptionsValidation `json:"validation,omitempty"`
}

// Validate validates this patch connections by id body options
func (m *PatchConnectionsByIDBodyOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePasswordPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePasswordComplexityOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePasswordDictionary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePasswordHistory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePasswordNoPersonalInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var patchConnectionsByIdBodyOptionsTypePasswordPolicyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["none","low","fair","good","excellent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		patchConnectionsByIdBodyOptionsTypePasswordPolicyPropEnum = append(patchConnectionsByIdBodyOptionsTypePasswordPolicyPropEnum, v)
	}
}

const (

	// PatchConnectionsByIDBodyOptionsPasswordPolicyNone captures enum value "none"
	PatchConnectionsByIDBodyOptionsPasswordPolicyNone string = "none"

	// PatchConnectionsByIDBodyOptionsPasswordPolicyLow captures enum value "low"
	PatchConnectionsByIDBodyOptionsPasswordPolicyLow string = "low"

	// PatchConnectionsByIDBodyOptionsPasswordPolicyFair captures enum value "fair"
	PatchConnectionsByIDBodyOptionsPasswordPolicyFair string = "fair"

	// PatchConnectionsByIDBodyOptionsPasswordPolicyGood captures enum value "good"
	PatchConnectionsByIDBodyOptionsPasswordPolicyGood string = "good"

	// PatchConnectionsByIDBodyOptionsPasswordPolicyExcellent captures enum value "excellent"
	PatchConnectionsByIDBodyOptionsPasswordPolicyExcellent string = "excellent"
)

// prop value enum
func (m *PatchConnectionsByIDBodyOptions) validatePasswordPolicyEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, patchConnectionsByIdBodyOptionsTypePasswordPolicyPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validatePasswordPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.PasswordPolicy) { // not required
		return nil
	}

	// value enum
	if err := m.validatePasswordPolicyEnum("passwordPolicy", "body", m.PasswordPolicy); err != nil {
		return err
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validatePasswordComplexityOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.PasswordComplexityOptions) { // not required
		return nil
	}

	if m.PasswordComplexityOptions != nil {
		if err := m.PasswordComplexityOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("password_complexity_options")
			}
			return err
		}
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validatePasswordDictionary(formats strfmt.Registry) error {

	if swag.IsZero(m.PasswordDictionary) { // not required
		return nil
	}

	if m.PasswordDictionary != nil {
		if err := m.PasswordDictionary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("password_dictionary")
			}
			return err
		}
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validatePasswordHistory(formats strfmt.Registry) error {

	if swag.IsZero(m.PasswordHistory) { // not required
		return nil
	}

	if m.PasswordHistory != nil {
		if err := m.PasswordHistory.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("password_history")
			}
			return err
		}
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validatePasswordNoPersonalInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.PasswordNoPersonalInfo) { // not required
		return nil
	}

	if m.PasswordNoPersonalInfo != nil {
		if err := m.PasswordNoPersonalInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("password_no_personal_info")
			}
			return err
		}
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptions) validateValidation(formats strfmt.Registry) error {

	if swag.IsZero(m.Validation) { // not required
		return nil
	}

	if m.Validation != nil {
		if err := m.Validation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("validation")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptions) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsPasswordComplexityOptions Password complexity options
// swagger:model PatchConnectionsByIDBodyOptionsPasswordComplexityOptions
type PatchConnectionsByIDBodyOptionsPasswordComplexityOptions struct {

	// Minimum password length
	// Maximum: 128
	// Minimum: 1
	MinLength int64 `json:"min_length,omitempty"`
}

// Validate validates this patch connections by ID body options password complexity options
func (m *PatchConnectionsByIDBodyOptionsPasswordComplexityOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMinLength(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordComplexityOptions) validateMinLength(formats strfmt.Registry) error {

	if swag.IsZero(m.MinLength) { // not required
		return nil
	}

	if err := validate.MinimumInt("password_complexity_options"+"."+"min_length", "body", int64(m.MinLength), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("password_complexity_options"+"."+"min_length", "body", int64(m.MinLength), 128, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordComplexityOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordComplexityOptions) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsPasswordComplexityOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsPasswordDictionary Options for password dictionary policy
// swagger:model PatchConnectionsByIDBodyOptionsPasswordDictionary
type PatchConnectionsByIDBodyOptionsPasswordDictionary struct {

	// Custom Password Dictionary. An array of up to 200 entries.
	// Max Items: 200
	Dictionary []string `json:"dictionary"`

	// enable
	// Required: true
	Enable *bool `json:"enable"`
}

// Validate validates this patch connections by ID body options password dictionary
func (m *PatchConnectionsByIDBodyOptionsPasswordDictionary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDictionary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordDictionary) validateDictionary(formats strfmt.Registry) error {

	if swag.IsZero(m.Dictionary) { // not required
		return nil
	}

	iDictionarySize := int64(len(m.Dictionary))

	if err := validate.MaxItems("password_dictionary"+"."+"dictionary", "body", iDictionarySize, 200); err != nil {
		return err
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordDictionary) validateEnable(formats strfmt.Registry) error {

	if err := validate.Required("password_dictionary"+"."+"enable", "body", m.Enable); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordDictionary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordDictionary) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsPasswordDictionary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsPasswordHistory Options for password history policy
// swagger:model PatchConnectionsByIDBodyOptionsPasswordHistory
type PatchConnectionsByIDBodyOptionsPasswordHistory struct {

	// enable
	// Required: true
	Enable *bool `json:"enable"`

	// size
	// Maximum: 24
	// Minimum: 0
	Size *int64 `json:"size,omitempty"`
}

// Validate validates this patch connections by ID body options password history
func (m *PatchConnectionsByIDBodyOptionsPasswordHistory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordHistory) validateEnable(formats strfmt.Registry) error {

	if err := validate.Required("password_history"+"."+"enable", "body", m.Enable); err != nil {
		return err
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordHistory) validateSize(formats strfmt.Registry) error {

	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := validate.MinimumInt("password_history"+"."+"size", "body", int64(*m.Size), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("password_history"+"."+"size", "body", int64(*m.Size), 24, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordHistory) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsPasswordHistory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo Options for password expiration policy
// swagger:model PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo
type PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo struct {

	// enable
	// Required: true
	Enable *bool `json:"enable"`
}

// Validate validates this patch connections by ID body options password no personal info
func (m *PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo) validateEnable(formats strfmt.Registry) error {

	if err := validate.Required("password_no_personal_info"+"."+"enable", "body", m.Enable); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsPasswordNoPersonalInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsValidation Options for validation
// swagger:model PatchConnectionsByIDBodyOptionsValidation
type PatchConnectionsByIDBodyOptionsValidation struct {

	// username
	Username *PatchConnectionsByIDBodyOptionsValidationUsername `json:"username,omitempty"`
}

// Validate validates this patch connections by ID body options validation
func (m *PatchConnectionsByIDBodyOptionsValidation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsValidation) validateUsername(formats strfmt.Registry) error {

	if swag.IsZero(m.Username) { // not required
		return nil
	}

	if m.Username != nil {
		if err := m.Username.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("validation" + "." + "username")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsValidation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsValidation) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsValidation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PatchConnectionsByIDBodyOptionsValidationUsername patch connections by ID body options validation username
// swagger:model PatchConnectionsByIDBodyOptionsValidationUsername
type PatchConnectionsByIDBodyOptionsValidationUsername struct {

	// max
	// Required: true
	// Maximum: 128
	Max *int64 `json:"max"`

	// min
	// Required: true
	// Minimum: 1
	Min *int64 `json:"min"`
}

// Validate validates this patch connections by ID body options validation username
func (m *PatchConnectionsByIDBodyOptionsValidationUsername) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyOptionsValidationUsername) validateMax(formats strfmt.Registry) error {

	if err := validate.Required("validation"+"."+"username"+"."+"max", "body", m.Max); err != nil {
		return err
	}

	if err := validate.MaximumInt("validation"+"."+"username"+"."+"max", "body", int64(*m.Max), 128, false); err != nil {
		return err
	}

	return nil
}

func (m *PatchConnectionsByIDBodyOptionsValidationUsername) validateMin(formats strfmt.Registry) error {

	if err := validate.Required("validation"+"."+"username"+"."+"min", "body", m.Min); err != nil {
		return err
	}

	if err := validate.MinimumInt("validation"+"."+"username"+"."+"min", "body", int64(*m.Min), 1, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsValidationUsername) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyOptionsValidationUsername) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyOptionsValidationUsername
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
