// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchConnectionsByIDBodyPasswordNoPersonalInfo Options for password expiration policy
// swagger:model patch_connections_by_id_body_password_no_personal_info
type PatchConnectionsByIDBodyPasswordNoPersonalInfo struct {

	// enable
	// Required: true
	Enable *bool `json:"enable"`
}

// Validate validates this patch connections by id body password no personal info
func (m *PatchConnectionsByIDBodyPasswordNoPersonalInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchConnectionsByIDBodyPasswordNoPersonalInfo) validateEnable(formats strfmt.Registry) error {

	if err := validate.Required("enable", "body", m.Enable); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyPasswordNoPersonalInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchConnectionsByIDBodyPasswordNoPersonalInfo) UnmarshalBinary(b []byte) error {
	var res PatchConnectionsByIDBodyPasswordNoPersonalInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
