// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchClientsByIDBodyScopes patch clients by id body scopes
// swagger:model patch_clients_by_id_body_scopes
type PatchClientsByIDBodyScopes interface{}
