// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchProviderResponseSettings Specific provider setting
// swagger:model patch_provider_response_settings
type PatchProviderResponseSettings interface{}
