// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchConnectionsByIDBodyUpstreamParams Options for adding parameters in the request to the upstream IdP
// swagger:model patch_connections_by_id_body_upstream_params
type PatchConnectionsByIDBodyUpstreamParams interface{}
