// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchClientsByIDBodyEchosign patch clients by id body echosign
// swagger:model patch_clients_by_id_body_echosign
type PatchClientsByIDBodyEchosign interface{}
