// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchSettingsResponse patch settings response
// swagger:model patch_settings_response
type PatchSettingsResponse struct {

	// A set of URLs that are valid to redirect to after logout from Auth0
	AllowedLogoutUrls []string `json:"allowed_logout_urls"`

	// change password
	ChangePassword *PatchSettingsResponseChangePassword `json:"change_password,omitempty"`

	// Default audience for API Authorization
	DefaultAudience string `json:"default_audience,omitempty"`

	// Name of the connection that will be used for password grants at the token endpoint. Only the following connection types are supported: LDAP, AD, Database Connections, Passwordless, Windows Azure Active Directory, ADFS
	DefaultDirectory string `json:"default_directory,omitempty"`

	// error page
	ErrorPage *PatchSettingsResponseErrorPage `json:"error_page,omitempty"`

	// flags
	Flags *PatchSettingsResponseFlags `json:"flags,omitempty"`

	// The friendly name of the tenant
	FriendlyName *string `json:"friendly_name,omitempty"`

	// guardian mfa page
	GuardianMfaPage *PatchSettingsResponseGuardianMfaPage `json:"guardian_mfa_page,omitempty"`

	// Force a user to login after they have been inactive for the specified number (unit: hours)
	IDLESessionLifetime *float64 `json:"idle_session_lifetime,omitempty"`

	// The URL of the tenant logo (recommended size: 150x150)
	PictureURL *string `json:"picture_url,omitempty"`

	// The selected sandbox version to be used for the extensibility environment
	SandboxVersion *string `json:"sandbox_version,omitempty"`

	// A set of available sandbox versions for the extensibility environment
	SandboxVersionsAvailable []string `json:"sandbox_versions_available"`

	// Login session lifetime, how long the session will stay valid (unit: hours)
	SessionLifetime *float64 `json:"session_lifetime,omitempty"`

	// User support email
	SupportEmail *string `json:"support_email,omitempty"`

	// User support url
	SupportURL *string `json:"support_url,omitempty"`
}

// Validate validates this patch settings response
func (m *PatchSettingsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrorPage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFlags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGuardianMfaPage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchSettingsResponse) validateChangePassword(formats strfmt.Registry) error {

	if swag.IsZero(m.ChangePassword) { // not required
		return nil
	}

	if m.ChangePassword != nil {
		if err := m.ChangePassword.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("change_password")
			}
			return err
		}
	}

	return nil
}

func (m *PatchSettingsResponse) validateErrorPage(formats strfmt.Registry) error {

	if swag.IsZero(m.ErrorPage) { // not required
		return nil
	}

	if m.ErrorPage != nil {
		if err := m.ErrorPage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error_page")
			}
			return err
		}
	}

	return nil
}

func (m *PatchSettingsResponse) validateFlags(formats strfmt.Registry) error {

	if swag.IsZero(m.Flags) { // not required
		return nil
	}

	if m.Flags != nil {
		if err := m.Flags.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("flags")
			}
			return err
		}
	}

	return nil
}

func (m *PatchSettingsResponse) validateGuardianMfaPage(formats strfmt.Registry) error {

	if swag.IsZero(m.GuardianMfaPage) { // not required
		return nil
	}

	if m.GuardianMfaPage != nil {
		if err := m.GuardianMfaPage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("guardian_mfa_page")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchSettingsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchSettingsResponse) UnmarshalBinary(b []byte) error {
	var res PatchSettingsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
