// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchClientsByIDBodyConcur patch clients by id body concur
// swagger:model patch_clients_by_id_body_concur
type PatchClientsByIDBodyConcur interface{}
