// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchClientsByIDResponseEncryptionKey patch clients by id response encryption key
// swagger:model patch_clients_by_id_response_encryption_key
type PatchClientsByIDResponseEncryptionKey struct {

	// cert
	Cert string `json:"cert,omitempty"`

	// pub
	Pub string `json:"pub,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this patch clients by id response encryption key
func (m *PatchClientsByIDResponseEncryptionKey) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchClientsByIDResponseEncryptionKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchClientsByIDResponseEncryptionKey) UnmarshalBinary(b []byte) error {
	var res PatchClientsByIDResponseEncryptionKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
