// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchSettingsResponseGuardianMfaPage Guardian page customization
// swagger:model patch_settings_response_guardian_mfa_page
type PatchSettingsResponseGuardianMfaPage struct {

	// <code>true</code> to use the custom html for Guardian page, <code>false</code> otherwise (default: <code>false</code>)
	Enabled *bool `json:"enabled,omitempty"`

	// Replace default Guardian page with a custom HTML (<a href='https://github.com/Shopify/liquid/wiki/Liquid-for-Designers' target='_new'>Liquid syntax</a> is supported)
	HTML string `json:"html,omitempty"`
}

// Validate validates this patch settings response guardian mfa page
func (m *PatchSettingsResponseGuardianMfaPage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchSettingsResponseGuardianMfaPage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchSettingsResponseGuardianMfaPage) UnmarshalBinary(b []byte) error {
	var res PatchSettingsResponseGuardianMfaPage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
