// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchProviderBodyCredentials patch provider body credentials
// swagger:model patch_provider_body_credentials
type PatchProviderBodyCredentials struct {

	// API Key
	// Required: true
	APIKey *string `json:"api_key"`
}

// Validate validates this patch provider body credentials
func (m *PatchProviderBodyCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchProviderBodyCredentials) validateAPIKey(formats strfmt.Registry) error {

	if err := validate.Required("api_key", "body", m.APIKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchProviderBodyCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchProviderBodyCredentials) UnmarshalBinary(b []byte) error {
	var res PatchProviderBodyCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
