// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchClientsByIDBodyWams patch clients by id body wams
// swagger:model patch_clients_by_id_body_wams
type PatchClientsByIDBodyWams struct {

	// The Windows Azure Mobile Services's master key
	Masterkey string `json:"masterkey,omitempty"`
}

// Validate validates this patch clients by id body wams
func (m *PatchClientsByIDBodyWams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchClientsByIDBodyWams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchClientsByIDBodyWams) UnmarshalBinary(b []byte) error {
	var res PatchClientsByIDBodyWams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
