// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchClientsByIDBodyFirebase patch clients by id body firebase
// swagger:model patch_clients_by_id_body_firebase
type PatchClientsByIDBodyFirebase struct {

	// The ID of the Service Account you have created (SDK 3+)
	ClientEmail string `json:"client_email,omitempty"`

	// Lifespan of the Token in seconds (SDK 3+)
	LifetimeInSeconds int64 `json:"lifetime_in_seconds,omitempty"`

	// The Private Key for signing the token. (SDK 3+)
	PrivateKey string `json:"private_key,omitempty"`

	// Optional. ID of the private key (SDK 3+)
	PrivateKeyID string `json:"private_key_id,omitempty"`

	// Firebase's secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this patch clients by id body firebase
func (m *PatchClientsByIDBodyFirebase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchClientsByIDBodyFirebase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchClientsByIDBodyFirebase) UnmarshalBinary(b []byte) error {
	var res PatchClientsByIDBodyFirebase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
