// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PatchUsersByIDBodyAppMetadata Data related to the user that does affect the application's core functionality. Send <code>null</code> to delete.
// swagger:model patch_users_by_id_body_app_metadata
type PatchUsersByIDBodyAppMetadata interface{}
