// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostTokensBody post tokens body
// swagger:model post_tokens_body
type PostTokensBody struct {

	// The JWT's aud claim. The client_id of the client for which it was issued
	Aud string `json:"aud,omitempty"`

	// The jti of the JWT to blacklist
	// Required: true
	Jti *string `json:"jti"`
}

// Validate validates this post tokens body
func (m *PostTokensBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJti(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostTokensBody) validateJti(formats strfmt.Registry) error {

	if err := validate.Required("jti", "body", m.Jti); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostTokensBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTokensBody) UnmarshalBinary(b []byte) error {
	var res PostTokensBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
