// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostClientsBodySalesforceAPI post clients body salesforce api
// swagger:model post_clients_body_salesforce_api
type PostClientsBodySalesforceAPI struct {

	// The Consumer Key assigned by Salesforce to the Connected App
	Clientid string `json:"clientid,omitempty"`

	// The community name
	CommunityName string `json:"communityName,omitempty"`

	// The community url section
	CommunityURLSection string `json:"community_url_section,omitempty"`

	// The name of the property in the user object that maps to a Salesforce username, for example: 'email'
	Principal string `json:"principal,omitempty"`
}

// Validate validates this post clients body salesforce api
func (m *PostClientsBodySalesforceAPI) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostClientsBodySalesforceAPI) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostClientsBodySalesforceAPI) UnmarshalBinary(b []byte) error {
	var res PostClientsBodySalesforceAPI
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
