// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostEmailTemplatesResponse post email templates response
// swagger:model post_email-templates_response
type PostEmailTemplatesResponse struct {

	// The body of the template.
	// Required: true
	Body *string `json:"body"`

	// Whether or not the template is enabled.
	// Required: true
	Enabled *bool `json:"enabled"`

	// The sender of the email.
	// Required: true
	From *string `json:"from"`

	// Whether or not we include the email as part of the returnUrl in the reset_email
	IncludeEmailInRedirect bool `json:"includeEmailInRedirect,omitempty"`

	// The URL to redirect the user to after a successful action.
	ResultURL string `json:"resultUrl,omitempty"`

	// The subject of the email.
	// Required: true
	Subject *string `json:"subject"`

	// The syntax of the template body.
	// Required: true
	Syntax *string `json:"syntax"`

	// The template name (verify_email, reset_email, welcome_email, blocked_account, stolen_credentials, enrollment_email, mfa_oob_code, <s>change_password</s> (legacy), <s>password_reset</s> (legacy)).
	// Required: true
	// Enum: [verify_email reset_email welcome_email blocked_account stolen_credentials enrollment_email mfa_oob_code change_password password_reset]
	Template *string `json:"template"`

	// The lifetime in seconds that the link within the email will be valid for.
	URLLifetimeInSeconds float64 `json:"urlLifetimeInSeconds,omitempty"`
}

// Validate validates this post email templates response
func (m *PostEmailTemplatesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSyntax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostEmailTemplatesResponse) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body); err != nil {
		return err
	}

	return nil
}

func (m *PostEmailTemplatesResponse) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *PostEmailTemplatesResponse) validateFrom(formats strfmt.Registry) error {

	if err := validate.Required("from", "body", m.From); err != nil {
		return err
	}

	return nil
}

func (m *PostEmailTemplatesResponse) validateSubject(formats strfmt.Registry) error {

	if err := validate.Required("subject", "body", m.Subject); err != nil {
		return err
	}

	return nil
}

func (m *PostEmailTemplatesResponse) validateSyntax(formats strfmt.Registry) error {

	if err := validate.Required("syntax", "body", m.Syntax); err != nil {
		return err
	}

	return nil
}

var postEmailTemplatesResponseTypeTemplatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["verify_email","reset_email","welcome_email","blocked_account","stolen_credentials","enrollment_email","mfa_oob_code","change_password","password_reset"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postEmailTemplatesResponseTypeTemplatePropEnum = append(postEmailTemplatesResponseTypeTemplatePropEnum, v)
	}
}

const (

	// PostEmailTemplatesResponseTemplateVerifyEmail captures enum value "verify_email"
	PostEmailTemplatesResponseTemplateVerifyEmail string = "verify_email"

	// PostEmailTemplatesResponseTemplateResetEmail captures enum value "reset_email"
	PostEmailTemplatesResponseTemplateResetEmail string = "reset_email"

	// PostEmailTemplatesResponseTemplateWelcomeEmail captures enum value "welcome_email"
	PostEmailTemplatesResponseTemplateWelcomeEmail string = "welcome_email"

	// PostEmailTemplatesResponseTemplateBlockedAccount captures enum value "blocked_account"
	PostEmailTemplatesResponseTemplateBlockedAccount string = "blocked_account"

	// PostEmailTemplatesResponseTemplateStolenCredentials captures enum value "stolen_credentials"
	PostEmailTemplatesResponseTemplateStolenCredentials string = "stolen_credentials"

	// PostEmailTemplatesResponseTemplateEnrollmentEmail captures enum value "enrollment_email"
	PostEmailTemplatesResponseTemplateEnrollmentEmail string = "enrollment_email"

	// PostEmailTemplatesResponseTemplateMfaOobCode captures enum value "mfa_oob_code"
	PostEmailTemplatesResponseTemplateMfaOobCode string = "mfa_oob_code"

	// PostEmailTemplatesResponseTemplateChangePassword captures enum value "change_password"
	PostEmailTemplatesResponseTemplateChangePassword string = "change_password"

	// PostEmailTemplatesResponseTemplatePasswordReset captures enum value "password_reset"
	PostEmailTemplatesResponseTemplatePasswordReset string = "password_reset"
)

// prop value enum
func (m *PostEmailTemplatesResponse) validateTemplateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, postEmailTemplatesResponseTypeTemplatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PostEmailTemplatesResponse) validateTemplate(formats strfmt.Registry) error {

	if err := validate.Required("template", "body", m.Template); err != nil {
		return err
	}

	// value enum
	if err := m.validateTemplateEnum("template", "body", *m.Template); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostEmailTemplatesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostEmailTemplatesResponse) UnmarshalBinary(b []byte) error {
	var res PostEmailTemplatesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
