// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PostClientsBodyCloudbees post clients body cloudbees
// swagger:model post_clients_body_cloudbees
type PostClientsBodyCloudbees interface{}
