// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PostUsersResponseAppMetadata Data related to the user that does affect the application's core functionality.
// swagger:model post_users_response_app_metadata
type PostUsersResponseAppMetadata interface{}
