// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PostClientsBodyOffice365 post clients body office365
// swagger:model post_clients_body_office365
type PostClientsBodyOffice365 interface{}
