// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostClientsBodySapAPI post clients body sap api
// swagger:model post_clients_body_sap_api
type PostClientsBodySapAPI struct {

	// Your SAP client ID
	Clientid string `json:"clientid,omitempty"`

	// The NameID element of the Subject can be used to express the user's identity
	NameIdentifierFormat string `json:"nameIdentifierFormat,omitempty"`

	// The requested scope for SAP APIs
	Scope string `json:"scope,omitempty"`

	// API calls to the token endpoint are authenticated with this password. Usually from a service account
	ServicePassword string `json:"servicePassword,omitempty"`

	// Your SAP OData server OAuth2 Token Endpoint URL
	TokenEndpointURL string `json:"tokenEndpointUrl,omitempty"`

	// The name of the property in the user object that maps to a SAP username, for example: 'email'
	UsernameAttribute string `json:"usernameAttribute,omitempty"`
}

// Validate validates this post clients body sap api
func (m *PostClientsBodySapAPI) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostClientsBodySapAPI) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostClientsBodySapAPI) UnmarshalBinary(b []byte) error {
	var res PostClientsBodySapAPI
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
