// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostClientsBodySalesforce post clients body salesforce
// swagger:model post_clients_body_salesforce
type PostClientsBodySalesforce struct {

	// The arbitrary logical URL that identifies the Saleforce resource. The format has to be 'https://whatever.com'
	EntityID string `json:"entity_id,omitempty"`
}

// Validate validates this post clients body salesforce
func (m *PostClientsBodySalesforce) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostClientsBodySalesforce) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostClientsBodySalesforce) UnmarshalBinary(b []byte) error {
	var res PostClientsBodySalesforce
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
